# This is a basic workflow to help you get started with Actions

name: Deploy WASM to GH Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          rustup target add wasm32-unknown-unknown
          curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
          source ~/.nvm/nvm.sh
          nvm install 10

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
          mkdir -p docs
          rm -rf ./docs/*
          wasm-pack build
          cd www && npm install
          npm run build
          mv ./dist/* ../docs
      - uses: actions/upload-pages-artifact@v1
      - uses: actions/deploy-pages@v1
